HYDRA_FULL_ERROR: 1

dataset: "MNIST"
batch_size: 128
optimizer_type: "sgd" #sgd or adam
learning_rate: 1e-6 #1e-2 for CCE, 1e-6 for MSE
algorithm: "WP" #BP or WP
pert_type: "Cent" #Cent or Clean
sigma: 1e-3
distribution: "normal"
nb_epochs: 100
loss_func: "mse" #CCE or MSE
seed: 42
device: "7"
loud_test: False
loud_train: True
comp_angles: True

wandb:
  use: True
  project: MetaWP
  entity: brai-lab
  name: WP-Cent-Angle-test