dataset: "MNIST"
batch_size: 128
optimizer_type: "sgd" #sgd or adam
algorithm: "WP" #BP or WP
sigma: 1e-3
distribution: "normal"
nb_epochs: 100
loss_func: "mse" #CCE or MSE
seed: 42
device: "4"
loud_test: True
loud_train: False
comp_angles: True
num_perts: 8
learning_rate: 1e-1 #1e-2 for CCE, 1e-6 for MSE
pert_type: "Clean" #Cent or Clean

project: MetaWP
entity: brai-lab
name: More-perts-angle-test