dataset: "MNIST"
batch_size: 128
optimizer_type: "sgd" #sgd or adam
algorithm: "WP" #BP or WP

sigma: 1e-3
distribution: "normal"
nb_epochs: 100
loss_func: "mse" #CCE or MSE
seed: 42
device: "6"
loud_test: False
loud_train: True
comp_angles: True
experiment: default


learning_rate: 
num_perts:
pert_type:

project: 
entity: 
name:
