#Setup 
nb_epochs: 5
bias: True
dataset: "CIFAR10"
batch_size: 128
seed: 42
device: "cuda:0"

#Testing settings
loud_test: True
loud_train: False
comp_angles: True
validation: True

#Model options
optimizer_type: "sgd" #sgd or adam
distribution: "normal"
loss_func: "cce" #CCE or MSE
learning_rate: "2**-18"
num_perts: 1
algorithm: "FFD" #ffd, cfd or bp
sigma: "2**-20"
meta_learning_rate: 0
mu_scaling_factor: 0
momentum: 0
dampening: False


#Wandb
project: MetaWP
entity: brai-lab
name: test if flops recording works
mode: "offline"







