dataset: "MNIST"
batch_size: 128
optimizer_type: "sgd" #sgd or adam
algorithm: "forw" #forw, cent or bp
sigma: 1e-3
distribution: "normal"
nb_epochs: 100
loss_func: "mse" #CCE or MSE
seed: 42
device: "cuda:0"
loud_test: True
loud_train: False
comp_angles: True
num_perts: 3
learning_rate: 1e-6 #1e-2 for CCE, 1e-6 for MSE

project: MetaWP
entity: brai-lab
name: More-perts-angle-test
mode: "offline"