#Setup 
nb_epochs: 100
bias: True
dataset: "MNIST"
batch_size: 128
seed: 42
device: "cuda:0"

#Testing settings
loud_test: True
loud_train: False
comp_angles: True
validation: True

#Model options
optimizer_type: "sgd" #sgd or adam
distribution: "normal"
loss_func: "cce" #CCE or MSE
learning_rate: "2**-25" 
num_perts: 1
algorithm: "ffd" #ffd, cfd or bp
sigma: "2**-16"
meta_learning_rate: "1e-10"
mu_scaling_factor: 0.1

#Wandb
project: MetaWP
entity: brai-lab
name: Mu test
mode: "offline"







