#Setup 
nb_epochs: 100
bias: True
dataset: "CIFAR10"
batch_size: 128
seed: 42
device: "cuda:0"

#Testing settings
loud_test: True
loud_train: False
comp_angles: False
validation: False

#Model options
optimizer_type: "sgd" #sgd or adam
distribution: "normal"
loss_func: "cce" #CCE or MSE
learning_rate: "2**-23"
num_perts: 32
algorithm: "meta_cfd" #ffd, cfd or bp
sigma: "2**-21"
meta_learning_rate: 0
mu_scaling_factor: 0
momentum: 0
dampening: False
nesterov: False
zero_masking: False
num_layers: 3
orthogonal_perts: False

#Wandb
project: MetaWP
entity: brai-lab
name: 
mode: "online"

