#Setup 
nb_epochs: 100
bias: True
dataset: "CIFAR10"
batch_size: 128
seed: 42
device: "cuda:0"

#Testing settings
loud_test: True
loud_train: False
comp_angles: False
validation: True

#Model options
optimizer_type: "sgd" #sgd or adam
distribution: "normal"
loss_func: "cce" #CCE or MSE
learning_rate: "2**-20"
num_perts: 1
algorithm: "ffd" #ffd, cfd or bp
sigma: "2**-16"
momentum: 0
dampening: False
nesterov: False
zero_masking: False
num_layers: 1

#Wandb
project: MetaWP
entity: brai-lab
name: 
mode: "offline"

