#Setup 
nb_epochs: 100
bias: True
dataset: "MNIST"
batch_size: 128
seed: 42
device: "cuda:0"

#Testing settings
loud_test: True
loud_train: False
comp_angles: False
validation: False

#Model options
optimizer_type: "sgd" #sgd or adam
distribution: "normal"
loss_func: "mse" #CCE or MSE
learning_rate: "2**-21" #1e-2 for CCE, 1e-6 for MSE
num_perts: 500
algorithm: "Cent" #forw, cent or bp
sigma: "2**-19"
meta_learning_rate: "1e-13"
switch: 0

#Wandb
project: MetaWP
entity: brai-lab
name: Mu test
mode: "offline"







