program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab 
name:  3-layer greedy (non-orthogonal) validation sweep, CIFAR10
method: grid
metric:
  goal: maximize
  name: validation/acc
parameters:
  algorithm:
    values:
      - greedy_FFD
      - greedy_CFD
  comp_angles:
    value: false
  dampening:
    value: false
  dataset:
    value: CIFAR10
  learning_rate:
    values:
      - 2**-20
      - 2**-21
      - 2**-22
      - 2**-23
      - 2**-24
      - 2**-25
  meta_learning_rate:
    value: 0
  momentum:
    value: 0
  mu_scaling_factor:
    value: 0
  nb_epochs:
    value: 150
  nesterov:
    value: false
  num_layers:
    value: nn3
  num_perts:
    values:
      - 32
  orthogonal_perts:
    value: false
  seed:
    values:
      - 42
  sigma:
    values:
      - 2**-12
      - 2**-17
  validation:
    value: true
  zero_masking:
    value: false


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


