program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab 
name:  3-layer validation sweep for meta mean learning CIFAR10, 1 perturbation, 150 epochs and two seeds
method: grid
metric:
  goal: maximize
  name: validation/acc
parameters:
    learning_rate:
        values:    
        - 2**-19
        - 2**-20
        - 2**-21
        - 2**-22
        - 2**-23
        - 2**-24
        - 2**-25
    algorithm:
        values: ["meta_FFD", "meta_CFD"]
    num_perts:
        values: [1]
    sigma:
        values: 
        - 2**-12
        - 2**-13     
        - 2**-14
        - 2**-15
        - 2**-16
        - 2**-18
        - 2**-19
        - 2**-20

    seed: 
        values: [42, 45]
    nb_epochs:
        value: 150
    dataset:
        value: "CIFAR10"
    validation: 
        value: True
    momentum: 
        value: 0 
    meta_learning_rate: 
        values:
        - 0.5
        - 0.7
        - 0.9
        - 0.99
    mu_scaling_factor: 
        values: 
        - 2**-17
        - 2**-18
        - 2**-19
        - 2**-20
        - 2**-21
        - 2**-22
        - 2**-23
        - 2**-24
        - 2**-25
    dampening:
        value: False 
    zero_masking:
        value: False
    nesterov:
        value: False
    num_layers: 
        value: 3

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


