program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name:  WP (best FFD, CCE loss) Test, CIFAR10, 1-layer, 1024
method: grid
metric:
  goal: maximize
  name: test/acc
parameters:
  algorithm:
    value: FFD
  dampening:
    value: false
  dataset:
    value: CIFAR10
  learning_rate:
    values:
      - 2**-24
  momentum:
    value: 0
  momentum_switch:
    value: true
  mu_scaling_factor:
    value: 0
  nb_epochs:
    value: 500
  num_perts:
    value: 1024
  seed:
    values:
      - 42
      - 45
      - 68
      - 89
      - 93
  sigma:
    value: 2**-19
  validation:
    value: false


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


