program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name: Meta learning rate and mu scaling factor test (lower lr's). CIFAR10, CFD, CCE. 
method: grid
metric:
  goal: minimize
  name: validation/loss
parameters:
    learning_rate:
        values: ["2**-25"]
    algorithm:
        values: ["CFD"]
    num_perts:
        values: [1]
    sigma:
        values: ["2**-16"]
    seed: 
        values: [42]
    meta_learning_rate:
        values: ["1e-5","1e-6","1e-7","1e-8", "1e-9","1e-10","1e-11"]
    mu_scaling_factor:
        values: [65536, 1, 1e-1, 1e-2, 1e-3]

command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


