dataset: "MNIST"
batch_size: 128
optimizer_type: "sgd" #sgd or adam
algorithm: "WP" #BP or WP

distribution: "normal"
nb_epochs: 50
loss_func: "mse" #CCE or MSE
seed: 42
device: "4"
loud_test: True
loud_train: False
comp_angles: True
experiment: default


learning_rate: 
num_perts:
pert_type:
sigma:
project: 
entity: 
name:
