#Setup 
nb_epochs: 100
bias: True
dataset: "CIFAR10"
batch_size: 128
seed:
device: "cuda:0"

#Testing settings
loud_test: True
loud_train: False
comp_angles: False
validation: True

#Model options
optimizer_type: "sgd" #sgd or adam
distribution: "normal"
loss_func: "cce" #CCE or MSE
learning_rate: 
num_perts:
algorithm:
sigma:
meta_learning_rate:
switch: 
mu_scaling_factor: 

#Wandb
project: 
entity: 
name:
mode: "online"
