program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name: 04.11 angle test
method: grid
metric:
  goal: maximize
  name: test/acc
parameters:
  learning_rate:
      values: [1e-6]
  algorithm:
      values: ["Forw", "Cent"]
  num_perts:
      values: [1, 8, 64, 256, 2048]
  sigma:
      values: [1e-3]
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


