#Setup 
nb_epochs: 500
bias: True
dataset: "MNIST"
batch_size: 128
seed:
device: "cuda:0"

#Testing settings
loud_test: True
loud_train: False
comp_angles: False
validation: False

#Model options
optimizer_type: "sgd" #sgd or adam
distribution: "normal"
loss_func: "mse" #CCE or MSE
learning_rate: 
num_perts:
algorithm:
sigma:

#Wandb
project: 
entity: 
name:
mode: "online"
