program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name: CFD/FFD - large perts, sigma test
method: grid
metric:
  goal: maximize
  name: test/acc
parameters:
  learning_rate:
      values: [1e-5, 1e-6, 1e-7]
  algorithm:
      values: ["Forw", "Cent", "BP"]
  num_perts:
      values: [1,8,64,512]
  sigma:
      values: [1e-2, 1e-3, 1e-4]
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


