program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name:  WP CIFAR10 parameter sweep, 2 perturbations, 1 layer network, CCE loss
method: grid
metric:
  goal: maximize
  name: validation/acc
parameters:
  algorithm:
    values: ["FFD", "CFD"]
  dampening:
    value: false
  dataset:
    value: CIFAR10
  learning_rate:
    values:
      - 2**-13
      - 2**-14
      - 2**-15
      - 2**-16
      - 2**-17
      - 2**-18
      - 2**-19
      - 2**-20
      - 2**-21
      - 2**-22
      - 2**-23
      - 2**-24
      - 2**-25
  momentum:
    value: 0
  momentum_switch:
    value: true
  mu_scaling_factor:
    value: 0
  nb_epochs:
    value: 100
  num_perts:
    values: [2]
  seed:
    value: 42
  sigma:
    values:
      - 2**-5
      - 2**-6
      - 2**-7
      - 2**-8
      - 2**-9
      - 2**-10
      - 2**-11
      - 2**-12
      - 2**-13
      - 2**-14
      - 2**-15
      - 2**-16
      - 2**-17
      - 2**-18
      - 2**-19
      - 2**-20
      - 2**-21
      - 2**-22
      - 2**-23
      - 2**-24
      - 2**-25
  validation:
    value: true


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


