program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name:  1-layer 1024 perturbations CFD test 
method: grid
metric:
  goal: maximize
  name: test/acc
parameters:
    learning_rate:
        values: [ "2**-20"]
    algorithm:
        values: ["CFD"]
    num_perts:
        values: [1024]
    sigma:
        values: ["2**-25"]
    seed: 
        values: [42,45,68,89,93]
    mu_scaling_factor:
        value: 0
    nb_epochs:
        value: 500
    dataset:
        value: "CIFAR10"
    validation: 
        value: False
    momentum: 
        value: 0
    dampening:
        value: False 


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


