program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name: 11.11 MNIST mean learning test
method: grid
metric:
  goal: minimize
  name: test/loss
parameters:
  learning_rate:
      values: ["2**-21"]
  algorithm:
      values: ["Forw", "Cent"]
  num_perts:
      values: [1, 32, 512]
  sigma:
      values: ["2**-19"]
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


