program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name:  CIFAR10 test (very large sigma)
method: grid
metric:
  goal: minimize
  name: test/loss
parameters:
    learning_rate:
        values: ["2**-21"]
    algorithm:
        values: ["CFD", "Grad_CFD"]
    num_perts:
        values: [1, 32, 512]
    sigma:
        values: ["2**-1"]
    seed: 
        values: [42]
    meta_learning_rate:
        values: [0]
    mu_scaling_factor:
        values: [0.9]
    nb_epochs:
        value: 500
    dataset:
        value: "CIFAR10"
    validation: 
        value: False
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


