program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name: 15.11 MNIST mean learning test
method: grid
metric:
  goal: minimize
  name: validation/loss
parameters:
  learning_rate:
      values: ["2**-21"]
  algorithm:
      values: ["Forw", "Cent"]
  num_perts:
      values: [1]
  sigma:
      values: ["2**-19"]
  meta_learning_rate:
      values: ["0**1", "10**-8", "10**-9", "10**-10", "10**-11"]
  switch: 
      values: [0,1]
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


