program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name: BP (sum loss) Test, MNIST
method: grid
metric:
  goal: minimize
  name: test/loss
parameters:
  learning_rate:
      values: ["2**-14"]
  algorithm:
      values: ["BP"]
  num_perts:
      values: [0]
  sigma:
      values: [0]
  seed:
    values: [42, 45, 68, 89, 93]
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


