program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab 
name:  1-layer FFD. 63 perturbations with best lr for 1 perturbation. Used in 1-32 perts experiment. Validation set.
method: grid
metric:
  goal: maximize
  name: validation/acc
parameters:
    learning_rate:
        values:    
        - 2**-24
    algorithm:
        value: "FFD"
    num_perts:
        value: 63
    sigma:
        value: "2**-19"
    seed:
        values:
        - 42
        - 45
        - 68
        - 89
        - 93
    nb_epochs:
        value: 100
    dataset:
        value: "CIFAR10"
    validation: 
        value: True
    comp_angles:
        value: True
    momentum: 
        value: 0
    dampening:
        value: False 
    zero_masking:
        value: False
    nesterov:
        value: False
    num_layers: 
        value: 1


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


