program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab 
name: Longer 1 perturbation validation sweep
method: grid
metric:
  goal: maximize
  name: validation/acc
parameters:
  algorithm:
    values:
    - FFD
    - CFD
  comp_angles:
    value: false
  dampening:
    value: false
  dataset:
    value: CIFAR10
  learning_rate:
    values:
    - 2**-22
    - 2**-23
    - 2**-24
    - 2**-25
    - 2**-26
  meta_learning_rate:
    value: 0
  momentum:
    value: 0
  mu_scaling_factor:
    value: 0
  nb_epochs:
    value: 200
  nesterov:
    value: false
  num_layers:
    values:
    - 3
  num_perts:
    values:
    - 1
  orthogonal_perts:
    value: false
  seed:
    values:
    - 42
  sigma:
    values:
    - 2**-12
    - 2**-18
    - 2**-24
  validation:
    value: true
  zero_masking:
    value: false
program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP


command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


