program: /home/markra/2nd-Order-Perturbations/run.py
project: MetaWP
entity: brai-lab
name: 18.11 CIFAR10 mean learning test
method: grid
metric:
  goal: minimize
  name: validation/loss
parameters:
    learning_rate:
        values: ["2**-25"]
    algorithm:
        values: ["Cent"]
    num_perts:
        values: [1,32]
    sigma:
        values: ["2**-16"]
    meta_learning_rate:
        values: ["0", "10**-9", "10**-10", "10**-11"]
    switch: 
        values: [0,1]
    seed: 
        values: [42]
    mu_scaling_factor:
        values: [0.1]
    
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}


