dataset: "MNIST"
batch_size: 128
optimizer_type: "sgd" #sgd or adam

distribution: "normal"
nb_epochs: 50
loss_func: "mse" #CCE or MSE
seed: 42
device: "cuda:0"
loud_test: True
loud_train: False
comp_angles: True
experiment: default
bias: True
mode: "online"

learning_rate: 
num_perts:
algorithm:
sigma:
project: 
entity: 
name:
